export const SET_STATUS_GET_USER = 'SET_STATUS_GET_USER'
export const SET_ERROR_GET_USER = 'SET_ERROR_GET_USER'
export const GET_USER = 'GET_USER'

export const SET_STATUS_SEARCH_USERS = 'SET_STATUS_SEARCH_USERS'
export const SET_ERROR_SEARCH_USERS = 'SET_ERROR_SEARCH_USERS'
export const SEARCH_USER = 'SEARCH_USER'
export const SEARCH_USER_CLEAR = 'SEARCH_USER_CLEAR'

export const ADD_ACCOUNTS = 'ADD_ACCOUNTS'
export const CLEAR_ACCOUNTS = 'CLEAR_ACCOUNTS'

export const ADD_SET = 'ADD_SET'
export const DELETE_SET = 'DELETE_SET'
export const UPDATE_SET = 'UPDATE_SET'
export const CLEAR_SETS = 'CLEAR_SETS'

export const ADD_TASK = 'ADD_TASK'
export const UPDATE_TASK = 'UPDATE_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const CLEAR_TASKS = 'CLEAR_TASKS'
export const SET_DELAY_IN_TASK = 'SET_DELAY_IN_TASK'

export const CREATE_ERROR = 'CREATE_ERROR'
export const SET_OPEN_ERROR = 'SET_OPEN_ERROR'

export const ADD_VIEWED_ACCOUNT = 'ADD_VIEWED_ACCOUNT'
export const DELETE_VIEWED_ACCOUNT = 'DELETE_VIEWED_ACCOUNT'
export const CLEAR_VIEWED_ACCOUNTS = 'CLEAR_VIEWED_ACCOUNTS'
